// CrystalWell Analytics — Markets Dashboard
// Reads three static files generated by the samuelstocks data pipeline
// (SEC EDGAR Form 4 + Yahoo Finance, refreshed on weekday mornings via a
// GitHub Actions workflow). No live network calls happen from this page —
// see data/dashboard/README.md for the pipeline that produces these files.
(function () {
  "use strict";

  // ---------- helpers ----------
  function isCEO(role) { var r = (role || "").toUpperCase(); return r.indexOf("CHIEF EXECUTIVE") !== -1 || /\bCEO\b/.test(r); }
  function isCFO(role) { var r = (role || "").toUpperCase(); return r.indexOf("CHIEF FINANCIAL") !== -1 || /\bCFO\b/.test(r); }
  function roleBadge(role) {
    if (isCEO(role)) return '<span class="role-badge role-ceo">CEO</span>';
    if (isCFO(role)) return '<span class="role-badge role-cfo">CFO</span>';
    return '<span class="role-badge role-dir">' + esc(role || "Insider") + "</span>";
  }
  function fmt(n) { return (!n && n !== 0) ? "—" : Number(n).toLocaleString("en-US"); }
  function fmtM(n) {
    if (!n && n !== 0) return "—";
    var v = Math.abs(Number(n));
    if (v >= 1e6) return "$" + (v / 1e6).toFixed(2) + "M";
    if (v >= 1e3) return "$" + (v / 1e3).toFixed(0) + "K";
    return "$" + v.toFixed(0);
  }
  function pctStr(p) { return (p > 0 ? "+" : "") + Number(p).toFixed(2) + "%"; }
  function pctClass(p) { return p < 0 ? "val-down" : "val-up"; }
  function thisMonth(s) {
    if (!s || s === "N/A") return false;
    var n = new Date(), d = new Date(s);
    return d.getFullYear() === n.getFullYear() && d.getMonth() === n.getMonth();
  }
  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"]/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c];
    });
  }
  function setText(id, v) { var n = document.getElementById(id); if (n) n.textContent = v; }
  function setHTML(id, v) { var n = document.getElementById(id); if (n) n.innerHTML = v; }

  function rsiPill(rsiLabel) {
    if (!rsiLabel) return '<span class="rsi-pill rsi-neutral">N/A</span>';
    var cls = "rsi-" + rsiLabel.level;
    var extra = "";
    if (rsiLabel.level === "oversold") extra = " · Oversold";
    if (rsiLabel.level === "overbought") extra = " · Overbought";
    return '<span class="rsi-pill ' + cls + '">' + esc(rsiLabel.label) + extra + "</span>";
  }
  function vs200Cell(pct) {
    if (pct === null || pct === undefined) return '<span class="val-muted">N/A</span>';
    var cls = pct >= 0 ? "vs200-up" : "vs200-down";
    var arrow = pct >= 0 ? "▲" : "▼";
    return '<div><span class="' + cls + '">' + arrow + " " + Math.abs(pct).toFixed(1) + '%</span>' +
      '<div class="vs200-sub">' + (pct >= 0 ? "above" : "below") + " 200d MA</div></div>";
  }
  function volBadge(signal, pct) {
    var pctStr2 = pct !== undefined ? " (" + (pct > 0 ? "+" : "") + pct + "%)" : "";
    if (signal === "light") return '<span class="vol-badge vol-light">↓ Light' + pctStr2 + "</span>";
    if (signal === "heavy") return '<span class="vol-badge vol-heavy">↑ Heavy' + pctStr2 + "</span>";
    return '<span class="vol-normal">Normal</span>';
  }
  var SIG_CLASS = { red: "sig-red", amber: "sig-amber", green: "sig-green", muted: "sig-muted" };
  function signalChip(sig) {
    if (!sig || !sig.name || sig.name === "—") return '<span class="val-muted">—</span>';
    var cls = SIG_CLASS[sig.color] || "sig-muted";
    var tip = sig.reason ? '<span class="tip">' + esc(sig.reason) + "</span>" : "";
    return '<span class="signal-chip-wrap"><span class="signal-chip ' + cls + '">' + (sig.icon || "") + " " + esc(sig.name) + "</span>" + tip + "</span>";
  }

  // ---------- tabs ----------
  function initTabs() {
    var tabs = document.querySelectorAll(".dash-tab");
    tabs.forEach(function (tab) {
      tab.addEventListener("click", function () {
        var name = tab.dataset.tab;
        document.querySelectorAll(".dash-panel").forEach(function (p) { p.classList.remove("active"); });
        document.querySelectorAll(".dash-tab").forEach(function (t) { t.classList.remove("active"); });
        document.getElementById("panel-" + name).classList.add("active");
        tab.classList.add("active");
        if (name === "keydates") loadKeyDates();
        if (name === "movement") loadPriceMovement();
      });
    });
  }

  // ---------- table search filter ----------
  function wireSearch(inputId, tbodyId, tickerColIndex) {
    var input = document.getElementById(inputId);
    if (!input) return;
    input.addEventListener("input", function () {
      var q = input.value.trim().toUpperCase();
      var rows = document.getElementById(tbodyId).querySelectorAll("tr");
      rows.forEach(function (row) {
        var cell = row.children[tickerColIndex];
        if (!cell) return;
        var match = cell.textContent.toUpperCase().indexOf(q) !== -1;
        row.style.display = match ? "" : "none";
      });
    });
  }

  // ---------- Insider Trading ----------
  function loadInsider() {
    fetch("data/dashboard/insider.json")
      .then(function (r) { if (!r.ok) throw new Error("insider.json"); return r.json(); })
      .then(renderInsider)
      .catch(function (e) { console.error(e); showFallback(["buys-body", "sells-body"], 8); });
  }

  function renderInsider(d) {
    var buys = d.buys || [], sells = d.sells || [];
    setText("s-total", buys.length + sells.length);
    setText("s-buys", buys.length);
    setText("s-sells", sells.length);
    setText("s-ceo-cfo", "CEO/CFO: " + buys.filter(function (x) { return isCEO(x.role) || isCFO(x.role); }).length);
    var uniq = {};
    buys.concat(sells).forEach(function (x) { uniq[x.ticker] = true; });
    setText("s-stocks", Object.keys(uniq).length);
    setText("insider-tab-count", buys.length + sells.length);

    setHTML("buys-body", buys.length === 0
      ? '<tr><td colspan="8" class="dash-empty">No insider buys found.</td></tr>'
      : buys.map(function (b) {
          return "<tr><td><span class=\"ticker-pill\">" + esc(b.ticker) + "</span></td>" +
            "<td title=\"" + esc(b.company || "") + "\">" + esc(b.company || "—") + "</td>" +
            "<td title=\"" + esc(b.insider || "") + "\">" + esc(b.insider || "—") + "</td>" +
            "<td title=\"" + esc(b.role || "") + "\">" + roleBadge(b.role) + "</td>" +
            '<td class="val-up">' + fmt(b.shares) + "</td>" +
            "<td>" + fmtM(b.value) + "</td>" +
            '<td class="val-muted">' + esc(b.date || "—") + "</td>" +
            '<td><a class="filing-link" href="' + esc(b.filing_url || "#") + '" target="_blank" rel="noopener">SEC ↗</a></td></tr>';
        }).join(""));

    setHTML("sells-body", sells.length === 0
      ? '<tr><td colspan="9" class="dash-empty">No insider sales found.</td></tr>'
      : sells.map(function (s) {
          return "<tr><td><span class=\"ticker-pill\">" + esc(s.ticker) + "</span></td>" +
            "<td title=\"" + esc(s.company || "") + "\">" + esc(s.company || "—") + "</td>" +
            "<td title=\"" + esc(s.insider || "") + "\">" + esc(s.insider || "—") + "</td>" +
            "<td title=\"" + esc(s.role || "") + "\">" + roleBadge(s.role) + "</td>" +
            '<td class="val-down">' + fmt(s.shares_sold) + "</td>" +
            "<td>" + fmt(s.shares_remaining) + "</td>" +
            '<td class="val-muted">' + esc(s.expiry || "—") + "</td>" +
            '<td class="val-muted">' + esc(s.date || "—") + "</td>" +
            '<td><a class="filing-link" href="' + esc(s.filing_url || "#") + '" target="_blank" rel="noopener">SEC ↗</a></td></tr>';
        }).join(""));

    var updated = document.getElementById("dash-updated-time");
    if (updated) updated.textContent = d.updated || "—";
  }

  // ---------- Key Dates ----------
  var keyDatesLoaded = false;
  function loadKeyDates() {
    if (keyDatesLoaded) return;
    fetch("data/dashboard/key_dates.json")
      .then(function (r) { if (!r.ok) throw new Error("key_dates.json"); return r.json(); })
      .then(function (d) { renderKeyDates(d); keyDatesLoaded = true; })
      .catch(function (e) { console.error(e); showFallback(["dividends-body", "earnings-body"], 6); });
  }

  function renderKeyDates(data) {
    var hasUpcoming = data.hasUpcoming || false;
    setText("div-table-title", hasUpcoming ? "Dividend dates — upcoming ex-dates" : "Dividend dates — recent ex-dates");
    setText("div-table-hint", hasUpcoming
      ? "Sorted by soonest ex-dividend date · Yield calculated from price · Source: Yahoo Finance"
      : "All announced ex-dates have passed — next dates not yet published · Source: Yahoo Finance");

    var divs = data.dividends || [], earns = data.earnings || [];
    setText("kd-paying", divs.filter(function (d) { return d.dividendRate > 0; }).length);
    setText("kd-upcoming", divs.filter(function (d) { return thisMonth(d.exDate); }).length);
    var sq = earns.filter(function (e) { return e.squeezeFlag; }).length;
    setText("kd-squeeze", sq);
    setText("kd-earnings", earns.filter(function (e) { return thisMonth(e.earningsDate); }).length);
    setText("keydates-tab-count", sq > 0 ? sq : "—");

    setHTML("dividends-body", divs.length === 0
      ? '<tr><td colspan="6" class="dash-empty">No dividend data.</td></tr>'
      : divs.map(function (d) {
          var exCls = (d.exDate && d.exDate !== "N/A" && d.exDate !== "Suspended") ? "val-up" : "val-muted";
          return "<tr><td><span class=\"ticker-pill\">" + esc(d.ticker) + "</span></td>" +
            "<td>" + esc(d.company || "—") + "</td>" +
            '<td class="' + exCls + '">' + esc(d.exDate || "—") + "</td>" +
            '<td class="val-up">' + (d.dividendRate > 0 ? "$" + d.dividendRate.toFixed(2) : "—") + "</td>" +
            "<td>" + (d.dividendYield > 0 ? d.dividendYield.toFixed(2) + "%" : "—") + "</td>" +
            '<td class="val-muted">' + (d.price > 0 ? "$" + d.price.toFixed(2) : "—") + "</td></tr>";
        }).join(""));

    setHTML("earnings-body", earns.length === 0
      ? '<tr><td colspan="5" class="dash-empty">No earnings data.</td></tr>'
      : earns.map(function (e) {
          var sqBadge = e.squeezeFlag ? '<span class="squeeze-badge">🔥 Squeeze</span>' : '<span class="val-muted">—</span>';
          var rCls = e.shortRatio >= 5 ? "val-down" : "val-muted";
          return "<tr><td><span class=\"ticker-pill\">" + esc(e.ticker) + "</span></td>" +
            "<td>" + esc(e.company || "—") + "</td>" +
            '<td class="val-up">' + esc(e.earningsDate || "—") + "</td>" +
            '<td class="' + rCls + '">' + (e.shortRatio > 0 ? e.shortRatio.toFixed(1) : "—") + "</td>" +
            '<td class="val-muted">' + (e.shortPct > 0 ? e.shortPct.toFixed(1) + "%" : "—") + "</td>" +
            "<td>" + sqBadge + "</td></tr>";
        }).join(""));

    setText("keydates-updated", "Data as of " + (data.updated || "—"));
  }

  // ---------- Price Movement ----------
  var priceMovementLoaded = false;
  function loadPriceMovement() {
    if (priceMovementLoaded) return;
    fetch("data/dashboard/price_movement.json")
      .then(function (r) { if (!r.ok) throw new Error("price_movement.json"); return r.json(); })
      .then(function (d) { renderPriceMovement(d); priceMovementLoaded = true; })
      .catch(function (e) { console.error(e); showFallback(["down-body", "up-body"], 11); });
  }

  function renderPriceMovement(data) {
    var downs = data.downStreaks || [], ups = data.upStreaks || [];
    var breakdowns = downs.filter(function (s) { return s.signal && s.signal.name === "Breakdown"; }).length;
    var bottomSignals = downs.filter(function (s) { return s.signal && (s.signal.name === "Near Bottom" || s.signal.name === "Strong Bottom"); }).length;
    var peakSignals = ups.filter(function (s) { return s.signal && (s.signal.name === "Near Peak" || s.signal.name === "Strong Peak"); }).length;

    setText("pm-down", downs.length);
    setText("pm-breakdown", breakdowns);
    setText("pm-bottom", bottomSignals);
    setText("pm-up", ups.length);
    setText("pm-peak", peakSignals);
    setText("movement-down-count", downs.length > 0 ? downs.length : "—");
    setText("movement-up-count", ups.length > 0 ? ups.length : "—");

    function movRow(s) {
      try {
        return "<tr><td><span class=\"ticker-pill\">" + esc(s.ticker) + "</span></td>" +
          "<td>" + esc(s.company) + "</td>" +
          '<td class="val-muted">$' + s.price.toFixed(2) + '<div class="vs200-sub">MA: $' + s.ma200 + "</div></td>" +
          "<td><div class=\"day-cell\"><div class=\"day-pct " + pctClass(s.day1.pct) + "\">" + pctStr(s.day1.pct) + "</div><div class=\"day-date\">" + esc(s.day1.date) + "</div></div></td>" +
          "<td><div class=\"day-cell\"><div class=\"day-pct " + pctClass(s.day2.pct) + "\">" + pctStr(s.day2.pct) + "</div><div class=\"day-date\">" + esc(s.day2.date) + "</div></div></td>" +
          "<td><div class=\"day-cell\"><div class=\"day-pct " + pctClass(s.day3.pct) + "\">" + pctStr(s.day3.pct) + "</div><div class=\"day-date\">" + esc(s.day3.date) + "</div></div></td>" +
          '<td class="' + (s.allDown ? "val-down" : "val-up") + '">' + pctStr(s.totalMove) + "</td>" +
          "<td>" + rsiPill(s.rsiLabel) + "</td>" +
          "<td>" + vs200Cell(s.vs200dPct) + "</td>" +
          "<td>" + volBadge(s.volSignal, s.volVsAvg) + "</td>" +
          "<td>" + signalChip(s.signal) + "</td></tr>";
      } catch (e) {
        console.warn("Skipping malformed price-movement row", s && s.ticker, e);
        return "";
      }
    }

    var downRows = downs.map(movRow).filter(Boolean);
    var upRows = ups.map(movRow).filter(Boolean);

    setHTML("down-body", downRows.length === 0
      ? '<tr><td colspan="11" class="dash-empty">No stocks down 3 consecutive days.</td></tr>'
      : downRows.join(""));
    setHTML("up-body", upRows.length === 0
      ? '<tr><td colspan="11" class="dash-empty">No stocks up 3 consecutive days.</td></tr>'
      : upRows.join(""));

    setText("movement-updated", "Data as of " + (data.updated || "—"));
  }

  function showFallback(tbodyIds, colspan) {
    tbodyIds.forEach(function (id) {
      setHTML(id, '<tr><td colspan="' + colspan + '" class="dash-loading">Data not yet available — run the pipeline workflow first.</td></tr>');
    });
  }

  function init() {
    initTabs();
    wireSearch("sells-search", "sells-body", 0);
    wireSearch("dividends-search", "dividends-body", 0);
    wireSearch("earnings-search", "earnings-body", 0);
    loadInsider();
  }

  document.addEventListener("DOMContentLoaded", init);
})();
